# Generated by Django 4.0.1 on 2022-02-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('archivo_cargado', models.FileField(upload_to='media/')),
                ('fecha_de_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=30)),
                ('nombre_manager', models.CharField(max_length=30)),
                ('telefono', models.FloatField(default=0)),
                ('email', models.EmailField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDePosicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_de_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Esperando', 'Esperando'), ('Denegado', 'Denegado')], max_length=30, null=True)),
                ('etapa', models.CharField(choices=[('Administracion', 'Administracion'), ('Aprobacion', 'Aprobacion'), ('Entevista', 'Entrevista')], max_length=30, null=True)),
                ('empresas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecruiterApp.empresas')),
                ('puesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecruiterApp.puestos')),
            ],
        ),
    ]
