# Generated by Django 4.0.1 on 2022-02-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managers',
            old_name='solicitud',
            new_name='solicitudes',
        ),
    ]
