# Generated by Django 4.0.1 on 2022-02-17 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruiterApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.AddField(
            model_name='empresas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
