# Generated by Django 4.0.1 on 2022-02-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0002_rename_solicitud_managers_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeposicion',
            name='email',
            field=models.EmailField(default='email', max_length=30, null=True),
        ),
    ]
