# Generated by Django 4.0.1 on 2022-02-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0002_delete_comentarios_empresas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddeposicion',
            name='nota',
            field=models.TextField(default='vacio', max_length=300),
        ),
        migrations.AddField(
            model_name='solicituddeposicion',
            name='seniority',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Semi Senior', 'Semi Senior'), ('Senior', 'Senior'), ('Gerente', 'Gerente')], max_length=30, null=True),
        ),
    ]
