# Generated by Django 4.0.1 on 2022-02-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0002_solicituddeposicion_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeposicion',
            name='resolucion',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Descartado', 'Descartado')], default='En Proceso', max_length=30, null=True),
        ),
    ]
