# Generated by Django 4.0.1 on 2022-02-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0003_alter_solicituddeposicion_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeposicion',
            name='email',
            field=models.EmailField(default='email@mail.com', max_length=30, null=True),
        ),
    ]
