# Generated by Django 4.0.1 on 2022-02-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0003_solicituddeposicion_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeposicion',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Esperando', 'Esperando'), ('Denegado', 'Denegado')], default='Esperando', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicituddeposicion',
            name='etapa',
            field=models.CharField(choices=[('Administracion', 'Administracion'), ('Aprobacion', 'Aprobacion'), ('Entevista', 'Entrevista')], default='Aprobacion', max_length=30),
        ),
    ]
