# Generated by Django 4.0.1 on 2022-02-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0004_alter_solicituddeposicion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeposicion',
            name='nota',
            field=models.TextField(default='Escriba información breve de utilidad en torno a la posición', max_length=300),
        ),
    ]
