# Generated by Django 4.0.1 on 2022-02-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0004_alter_solicituddeposicion_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managers',
            name='solicitudes',
        ),
        migrations.AddField(
            model_name='solicituddeposicion',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecruiterApp.managers'),
        ),
    ]
