# Generated by Django 4.0.1 on 2022-02-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0004_departamentorecruiter_departamentogerencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeposicion',
            name='etapa',
            field=models.CharField(choices=[('Administracion', 'Administracion'), ('Aprobacion', 'Aprobacion'), ('Entrevista', 'Entrevista')], default='Aprobacion', max_length=30, null=True),
        ),
    ]
