# Generated by Django 4.0.1 on 2022-02-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0005_remove_managers_solicitudes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecruiterApp.empresas'),
        ),
    ]
