# Generated by Django 4.0.1 on 2022-02-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruiterApp', '0007_alter_solicituddeposicion_etapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivos',
        ),
        migrations.AddField(
            model_name='solicituddeposicion',
            name='cargar_archivos',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
